import type { EconomicEvent, EventCategory, EventImpact } from './types';

/**
 * Top 15 high-impact economic events to track
 * Data structure includes typical impact patterns for crypto markets
 */
export const TOP_ECONOMIC_EVENTS: Partial<EconomicEvent>[] = [
  {
    name: 'Fed Meeting Minutes (FOMC)',
    country: 'US',
    category: 'central_bank' as EventCategory,
    impact: 'HIGH' as EventImpact,
    frequency: 'Monthly (8 times/year)',
    source: 'Federal Reserve',
    sourceUrl: 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
    description: 'Detailed record of the Federal Open Market Committee meeting discussions, revealing policymakers\' economic outlook and future monetary policy direction. Provides insights into interest rate decisions and inflation concerns.',
    cryptoImpact: 'FOMC minutes heavily influence crypto markets as they signal future interest rate policy. Hawkish tones (higher rates expected) typically trigger selloffs as investors move to safer assets. Dovish language (rates staying low) often sparks rallies as risk appetite increases. Watch for language around inflation targets and employment data.',
    btcAvgImpact: 3.5,
    ethAvgImpact: 4.2,
    spxAvgImpact: 1.8,
    volumeSpike: 250,
    primaryWindowStart: '14:00',
    primaryWindowEnd: '16:00',
    extendedWindowStart: '14:00',
    extendedWindowEnd: '18:00',
  },
  {
    name: 'US CPI Data',
    country: 'US',
    category: 'inflation' as EventCategory,
    impact: 'HIGH' as EventImpact,
    frequency: 'Monthly',
    source: 'Bureau of Labor Statistics',
    sourceUrl: 'https://www.bls.gov/cpi/',
    description: 'Consumer Price Index measures the average change in prices paid by consumers for goods and services. Core CPI excludes volatile food and energy prices. This is the primary inflation gauge used by the Federal Reserve.',
    cryptoImpact: 'CPI is one of the most volatile events for crypto. Higher-than-expected CPI suggests persistent inflation, potentially leading to Fed rate hikes and crypto selloffs. Lower CPI signals cooling inflation, often triggering significant rallies. Expect 200-500% volume spikes and 3-6% price swings within minutes of release.',
    btcAvgImpact: 4.2,
    ethAvgImpact: 5.1,
    spxAvgImpact: 2.2,
    volumeSpike: 300,
    primaryWindowStart: '13:30',
    primaryWindowEnd: '15:30',
    extendedWindowStart: '13:30',
    extendedWindowEnd: '17:00',
  },
  {
    name: 'Non-Farm Payrolls (NFP)',
    country: 'US',
    category: 'employment' as EventCategory,
    impact: 'HIGH' as EventImpact,
    frequency: 'Monthly',
    source: 'Bureau of Labor Statistics',
    sourceUrl: 'https://www.bls.gov/ces/',
    description: 'Monthly report on the number of jobs added or lost in the US economy, excluding farm workers, government employees, and non-profit organization employees. Released first Friday of every month with unemployment rate and wage growth data.',
    cryptoImpact: 'Strong jobs data can be bearish for crypto as it signals the Fed may keep rates higher for longer. Weak employment numbers often boost crypto as they increase odds of rate cuts. Pay attention to wage growth - higher wages fuel inflation concerns. Markets often reverse initial moves as traders digest implications.',
    btcAvgImpact: 3.8,
    ethAvgImpact: 4.5,
    spxAvgImpact: 2.0,
    volumeSpike: 280,
    primaryWindowStart: '13:30',
    primaryWindowEnd: '15:30',
    extendedWindowStart: '13:30',
    extendedWindowEnd: '17:00',
  },
  {
    name: 'FOMC Rate Decision',
    country: 'US',
    category: 'central_bank' as EventCategory,
    impact: 'HIGH' as EventImpact,
    frequency: '8 times/year',
    source: 'Federal Reserve',
    sourceUrl: 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm',
    description: 'The Federal Reserve announces changes to the federal funds rate, the interest rate at which banks lend to each other overnight. Includes economic projections and the dot plot showing Fed members\' rate expectations. Press conference follows 30 minutes after.',
    cryptoImpact: 'THE most important event for crypto markets. Rate hikes strengthen the dollar and hurt crypto as borrowing costs rise. Rate cuts or pauses often trigger massive rallies. Jerome Powell\'s press conference at 2:30 PM ET creates a second wave of volatility. Expect 5-10% swings and 300-400% volume increases. Position management is critical.',
    btcAvgImpact: 5.2,
    ethAvgImpact: 6.0,
    spxAvgImpact: 2.5,
    volumeSpike: 350,
    primaryWindowStart: '14:00',
    primaryWindowEnd: '16:00',
    extendedWindowStart: '14:00',
    extendedWindowEnd: '18:00',
  },
  {
    name: 'US GDP (Preliminary/Final)',
    country: 'US',
    category: 'gdp_growth' as EventCategory,
    impact: 'HIGH' as EventImpact,
    frequency: 'Quarterly',
    source: 'Bureau of Economic Analysis',
    sourceUrl: 'https://www.bea.gov/data/gdp',
    description: 'Quarterly measure of the total value of all goods and services produced in the US economy. Released in three versions: advance, preliminary, and final. Annualized growth rate compared to previous quarter.',
    cryptoImpact: 'GDP impacts crypto through growth expectations and recession fears. Strong GDP above 3% can pressure crypto if it signals Fed won\'t cut rates. Negative GDP or below 1% growth often triggers flight to safety, initially hurting crypto but potentially helping if it forces Fed dovishness. Less volatile than CPI or NFP but still moves markets 2-4%.',
    btcAvgImpact: 2.8,
    ethAvgImpact: 3.2,
    spxAvgImpact: 1.5,
    volumeSpike: 220,
    primaryWindowStart: '13:30',
    primaryWindowEnd: '15:30',
    extendedWindowStart: '13:30',
    extendedWindowEnd: '16:00',
  },
  {
    name: 'ECB Rate Decision',
    country: 'EU',
    category: 'central_bank' as EventCategory,
    impact: 'HIGH' as EventImpact,
    frequency: '8 times/year',
    source: 'European Central Bank',
    sourceUrl: 'https://www.ecb.europa.eu/press/calendars/mgcgc/html/index.en.html',
    description: 'European Central Bank sets interest rates for the eurozone, the world\'s second-largest economic bloc. Decision affects deposit facility rate, main refinancing rate, and marginal lending rate. ECB President press conference follows.',
    cryptoImpact: 'While less impactful than Fed decisions, ECB actions still move global crypto markets. Divergence from Fed policy creates cross-currency flows affecting Bitcoin. Rate hikes strengthen euro vs dollar, providing indirect crypto support. Europe\'s regulatory stance on crypto adds extra weight to ECB communications. Expect 2-4% moves.',
    btcAvgImpact: 3.2,
    ethAvgImpact: 3.8,
    spxAvgImpact: 1.2,
    volumeSpike: 240,
    primaryWindowStart: '12:45',
    primaryWindowEnd: '14:45',
    extendedWindowStart: '12:45',
    extendedWindowEnd: '16:00',
  },
  {
    name: 'US PPI Data',
    country: 'US',
    category: 'inflation' as EventCategory,
    impact: 'HIGH' as EventImpact,
    frequency: 'Monthly',
    source: 'Bureau of Labor Statistics',
    sourceUrl: 'https://www.bls.gov/ppi/',
    description: 'Producer Price Index measures average change in selling prices received by domestic producers. Leading indicator of consumer inflation as producer costs eventually pass through to consumers. Released day before CPI.',
    cryptoImpact: 'PPI is a preview of CPI trends and sets tone for next day\'s CPI reaction. Rising PPI warns of future consumer price increases, pressuring crypto ahead of CPI. Falling PPI gives crypto relief rally. Smart traders use PPI to position for CPI. Lower impact than CPI but still creates 2-3% moves and 150-200% volume spikes.',
    btcAvgImpact: 2.5,
    ethAvgImpact: 3.0,
    spxAvgImpact: 1.3,
    volumeSpike: 200,
    primaryWindowStart: '13:30',
    primaryWindowEnd: '15:30',
    extendedWindowStart: '13:30',
    extendedWindowEnd: '16:00',
  },
  {
    name: 'Unemployment Rate',
    country: 'US',
    category: 'employment' as EventCategory,
    impact: 'HIGH' as EventImpact,
    frequency: 'Monthly',
    source: 'Bureau of Labor Statistics',
    sourceUrl: 'https://www.bls.gov/cps/',
    description: 'Percentage of labor force that is jobless and actively seeking employment. Released simultaneously with Non-Farm Payrolls. Also includes labor force participation rate and underemployment figures (U-6).',
    cryptoImpact: 'Released with NFP so impact is combined. Rising unemployment (above 4%) signals economic weakness, potentially forcing Fed to cut rates - initially bearish but eventually bullish for crypto. Low unemployment keeps Fed hawkish. Watch for divergence between NFP and unemployment rate for volatility. Market often focuses more on NFP number.',
    btcAvgImpact: 2.2,
    ethAvgImpact: 2.8,
    spxAvgImpact: 1.0,
    volumeSpike: 180,
    primaryWindowStart: '13:30',
    primaryWindowEnd: '15:30',
    extendedWindowStart: '13:30',
    extendedWindowEnd: '16:00',
  },
  {
    name: 'Retail Sales',
    country: 'US',
    category: 'retail_consumer' as EventCategory,
    impact: 'MEDIUM' as EventImpact,
    frequency: 'Monthly',
    source: 'US Census Bureau',
    sourceUrl: 'https://www.census.gov/retail/index.html',
    description: 'Measures total receipts of retail stores, tracking consumer spending which accounts for 70% of US economic activity. Includes both brick-and-mortar and online sales. Core retail sales excludes autos and gas.',
    cryptoImpact: 'Strong retail sales show healthy consumer spending but can pressure crypto by reducing rate cut expectations. Weak sales signal economic slowdown, potentially forcing Fed dovishness - short-term bearish, longer-term bullish. Holiday season reports (Nov-Dec) have extra impact. Generally creates 1-2.5% price moves with moderate volume increases.',
    btcAvgImpact: 2.0,
    ethAvgImpact: 2.5,
    spxAvgImpact: 0.9,
    volumeSpike: 150,
    primaryWindowStart: '13:30',
    primaryWindowEnd: '15:30',
    extendedWindowStart: '13:30',
    extendedWindowEnd: '16:00',
  },
  {
    name: 'PMI Manufacturing (US)',
    country: 'US',
    category: 'manufacturing' as EventCategory,
    impact: 'MEDIUM' as EventImpact,
    frequency: 'Monthly',
    source: 'Institute for Supply Management',
    sourceUrl: 'https://www.ismworld.org/',
    description: 'Purchasing Managers\' Index surveys manufacturing executives on new orders, production, employment, deliveries, and inventories. Reading above 50 indicates expansion, below 50 signals contraction. Leading economic indicator.',
    cryptoImpact: 'PMI provides early warning of economic direction. Strong PMI (above 55) can hurt crypto by keeping Fed hawkish. Weak PMI (below 50) signals recession risk - initially bearish but forces Fed toward cuts. Services PMI released same week matters more for US economy. Creates modest 1-2% moves but can set weekly trend.',
    btcAvgImpact: 1.8,
    ethAvgImpact: 2.2,
    spxAvgImpact: 0.8,
    volumeSpike: 140,
    primaryWindowStart: '14:00',
    primaryWindowEnd: '16:00',
    extendedWindowStart: '14:00',
    extendedWindowEnd: '16:00',
  },
  {
    name: 'Fed Chair Speech',
    country: 'US',
    category: 'central_bank' as EventCategory,
    impact: 'HIGH' as EventImpact,
    frequency: 'Multiple times/year',
    source: 'Federal Reserve',
    sourceUrl: 'https://www.federalreserve.gov/newsevents/speeches.htm',
    description: 'Federal Reserve Chair (Jerome Powell) delivers remarks at conferences, congressional testimonies, or economic symposiums. Q&A sessions often follow. Comments on inflation, employment, and monetary policy direction move markets significantly.',
    cryptoImpact: 'Powell\'s words are gospel for crypto traders. Even minor shifts in tone create huge swings. Listen for "higher for longer" (bearish), "patient approach" (neutral), or "inflation cooling" (bullish). Jackson Hole and semi-annual Congressional testimony are most important. Unscripted Q&A creates most volatility. Expect 2-4% moves, sometimes 5-8% on major surprises.',
    btcAvgImpact: 3.0,
    ethAvgImpact: 3.5,
    spxAvgImpact: 1.5,
    volumeSpike: 220,
    primaryWindowStart: '00:00',
    primaryWindowEnd: '23:59',
    extendedWindowStart: '00:00',
    extendedWindowEnd: '23:59',
  },
  {
    name: 'ECB Meeting Minutes',
    country: 'EU',
    category: 'central_bank' as EventCategory,
    impact: 'MEDIUM' as EventImpact,
    frequency: '8 times/year',
    source: 'European Central Bank',
    sourceUrl: 'https://www.ecb.europa.eu/press/accounts/html/index.en.html',
    description: 'Account of ECB Governing Council monetary policy meetings, revealing internal debates and future policy leanings. Released 4 weeks after each meeting. Provides context for rate decisions and quantitative easing programs.',
    cryptoImpact: 'Less impactful than Fed minutes but still relevant for global macro. Reveals splits among ECB members and future policy direction. Important for EUR/USD pair which affects Bitcoin dollar pricing. Watch for hints about ending QE or balance sheet reduction. Typically creates 1-2% moves during European trading hours with limited US impact.',
    btcAvgImpact: 1.5,
    ethAvgImpact: 1.8,
    spxAvgImpact: 0.6,
    volumeSpike: 120,
    primaryWindowStart: '12:30',
    primaryWindowEnd: '14:30',
    extendedWindowStart: '12:30',
    extendedWindowEnd: '15:00',
  },
  {
    name: 'Consumer Confidence',
    country: 'US',
    category: 'retail_consumer' as EventCategory,
    impact: 'MEDIUM' as EventImpact,
    frequency: 'Monthly',
    source: 'Conference Board',
    sourceUrl: 'https://www.conference-board.org/topics/consumer-confidence',
    description: 'Survey measuring consumer attitudes about current and future economic conditions. Based on 3,000 households. Includes present situation and expectations indexes. Above 100 indicates optimism, below shows pessimism.',
    cryptoImpact: 'Consumer sentiment affects risk appetite. High confidence (above 110) supports risk assets like crypto as consumers feel secure. Plunging confidence (below 90) signals recession fears, driving flight to safety - short-term crypto selloff. However, extreme pessimism often marks bottoms. Creates modest 1-1.5% moves, more relevant as trend indicator than immediate price driver.',
    btcAvgImpact: 1.2,
    ethAvgImpact: 1.5,
    spxAvgImpact: 0.5,
    volumeSpike: 110,
    primaryWindowStart: '14:00',
    primaryWindowEnd: '16:00',
    extendedWindowStart: '14:00',
    extendedWindowEnd: '16:00',
  },
  {
    name: 'Housing Starts',
    country: 'US',
    category: 'gdp_growth' as EventCategory,
    impact: 'MEDIUM' as EventImpact,
    frequency: 'Monthly',
    source: 'US Census Bureau',
    sourceUrl: 'https://www.census.gov/construction/nrc/index.html',
    description: 'Number of new residential construction projects begun each month. Includes single-family homes and multi-unit buildings. Released with building permits data. Leading indicator of economic health as housing drives related industries.',
    cryptoImpact: 'Housing data has limited direct crypto impact but signals economic health and Fed policy direction. Strong starts show resilient economy despite high rates - potentially keeping Fed hawkish. Collapsing starts (below 1.3M annually) warn of recession, eventually forcing rate cuts. Most useful as confirmation of broader trends rather than trading catalyst. Expect 0.5-1.2% moves.',
    btcAvgImpact: 1.0,
    ethAvgImpact: 1.2,
    spxAvgImpact: 0.4,
    volumeSpike: 100,
    primaryWindowStart: '13:30',
    primaryWindowEnd: '15:30',
    extendedWindowStart: '13:30',
    extendedWindowEnd: '15:30',
  },
  {
    name: 'Initial Jobless Claims',
    country: 'US',
    category: 'employment' as EventCategory,
    impact: 'MEDIUM' as EventImpact,
    frequency: 'Weekly',
    source: 'Department of Labor',
    sourceUrl: 'https://www.dol.gov/ui/data.pdf',
    description: 'Weekly count of Americans filing for unemployment benefits for the first time. Most timely labor market indicator. Continuing claims (second-week filers) also released. Below 220k is strong, above 260k signals weakness.',
    cryptoImpact: 'Weekly pulse check on employment health. Spiking claims (above 250k) warn of labor market cracks, potentially accelerating Fed pivot - mixed signal for crypto. Steady low claims keep Fed hawkish. Less impactful than monthly NFP but can foreshadow surprises. Creates minor 0.5-1% moves but worth watching as early warning system for bigger employment trends.',
    btcAvgImpact: 0.8,
    ethAvgImpact: 1.0,
    spxAvgImpact: 0.3,
    volumeSpike: 90,
    primaryWindowStart: '13:30',
    primaryWindowEnd: '14:30',
    extendedWindowStart: '13:30',
    extendedWindowEnd: '15:00',
  },
];

/**
 * Get icon for event category
 */
export function getCategoryIcon(category: EventCategory): string {
  const icons: Record<EventCategory, string> = {
    central_bank: '🏦',
    inflation: '📊',
    employment: '👔',
    manufacturing: '🏭',
    gdp_growth: '📈',
    retail_consumer: '💰',
  };
  return icons[category] || '📅';
}

/**
 * Get color class for impact level
 */
export function getImpactColor(impact: EventImpact): string {
  switch (impact) {
    case 'HIGH':
      return 'text-red-500';
    case 'MEDIUM':
      return 'text-yellow-500';
    case 'LOW':
      return 'text-gray-500';
    default:
      return 'text-gray-400';
  }
}

/**
 * Get badge emoji for impact level
 */
export function getImpactBadge(impact: EventImpact): string {
  switch (impact) {
    case 'HIGH':
      return '🔴';
    case 'MEDIUM':
      return '🟡';
    case 'LOW':
      return '⚪';
    default:
      return '⚪';
  }
}
